CREATE TABLE [User] (
    UserID NVARCHAR(20) NOT NULL PRIMARY KEY,
    UserName NVARCHAR(100) NOT NULL,
    Email NVARCHAR(256) NOT NULL UNIQUE,
    Account NVARCHAR(20) NOT NULL,
    PasswordHash NVARCHAR(256) NOT NULL,
    PasswordSalt NVARCHAR(256) NOT NULL
);

CREATE TABLE Product (
    No INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    ProductName NVARCHAR(200) NOT NULL,
    Price DECIMAL(18, 2) NOT NULL,
    FeeRate DECIMAL(9, 4) NOT NULL
);

CREATE TABLE LikeList (
    SN INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    UserID NVARCHAR(20) NOT NULL,
    ProductNo INT NOT NULL,
    OrderQty INT NOT NULL,
    Account NVARCHAR(20) NOT NULL,
    TotalFee DECIMAL(18, 2) NOT NULL,
    TotalAmount DECIMAL(18, 2) NOT NULL,
    Email NVARCHAR(256) NOT NULL,
    CONSTRAINT FK_LikeList_User FOREIGN KEY (UserID) REFERENCES [User](UserID),
    CONSTRAINT FK_LikeList_Product FOREIGN KEY (ProductNo) REFERENCES Product(No)
);
